version: '3.7'
services:
  connector:
    image: parasite-api
    command: connector
    environment:
      - NODE_ENV=development
    ports:
      - 80:80
    deploy:
      replicas: 2
  game:
    image: parasite-api
    command: game
    environment:
      - NODE_ENV=development
    deploy:
      replicas: 2
  redis:
    image: redis:alpine
  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_DATABASE=parasite
      - MYSQL_ROOT_PASSWORD=password
